server:
  port: 9003
spring:
  application:
    name: star-forum-article
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/star_forum_article?characterEncoding=utf-8
    username: root
    password: 123

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
